#!/usr/bin/env bash

bin_dir=~/.local/bin.ccache

mkdir -p "$bin_dir"

ccache_path=$(command -v ccache)
if (( $? )); then
    printf "ccache not found!\n" >&2

    exit 1
fi

ln -sf "$ccache_path" "$bin_dir/gcc"
ln -sf "$ccache_path" "$bin_dir/g++"
ln -sf "$ccache_path" "$bin_dir/clang"
ln -sf "$ccache_path" "$bin_dir/clang++"
