#!/usr/bin/env bash

_bin_dir=~/.local/bin.ccache

mkdir -p "$_bin_dir"

_ccache_path=$(command -v ccache)
if (( $? )); then
    printf "ccache not found!\n" >&2

    exit 1
fi

ln -sf "$_ccache_path" "$_bin_dir/gcc"
ln -sf "$_ccache_path" "$_bin_dir/g++"
ln -sf "$_ccache_path" "$_bin_dir/clang"
ln -sf "$_ccache_path" "$_bin_dir/clang++"
