#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-3.8.0}

pkg_tag=protobuf-$pkg_ver

git_url=https://github.com/protocolbuffers/protobuf.git

git_tag=v$pkg_ver

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build

mkdir -p "$src_dir" "$bld_dir"

if [[ ! -d $src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch "$git_tag" "$git_url" "$src_dir"
fi

cd "$src_dir"

./autogen.sh

cd "$bld_dir"

"$src_dir/configure" "CFLAGS=-fPIC -fvisibility=hidden -std=c99" "CXXFLAGS=-fPIC -fvisibility=hidden -std=c++14"\
    --disable-shared\
    --prefix="$HOME/.local/stow/$pkg_tag"

execute_job make --jobs

make install
