#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-3.21.0}

pkg_tag=cmake-$pkg_ver

pkg_dir=~/.local/stow/$pkg_tag

pkg_tar=~/.cache/stow/$pkg_tag.tgz

pkg_url=https://github.com/Kitware/CMake/releases/download/v$pkg_ver/cmake-$pkg_ver-linux-x86_64.tar.gz

if [[ ! -f $pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$pkg_tar" "$pkg_url"
fi

mkdir -p "$pkg_dir" && cd "$_"

tar xvf "$pkg_tar" --strip-components 1

cat << EOF > "$pkg_dir/.stow-local-ignore"
^/doc$
^/man$
EOF
