#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-4.6.3}

pkg_tag=ccache-$pkg_ver

pkg_dir=~/.local/stow/$pkg_tag

pkg_tar=~/.cache/stow/$pkg_tag.tar.xz

pkg_url=https://github.com/ccache/ccache/releases/download/v$pkg_ver/ccache-$pkg_ver-linux-x86_64.tar.xz

if [[ ! -f $pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$pkg_tar" "$pkg_url"
fi

mkdir -p "$pkg_dir/bin" && cd "$_"

tar --extract --file "$pkg_tar" --strip-components 1 ccache-$pkg_ver-linux-x86_64/ccache
