#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-2.2.0}

pkg_tag=ag-$pkg_ver

git_url=https://github.com/ggreer/the_silver_searcher.git

git_tag=$pkg_ver

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build

mkdir -p "$src_dir" "$bld_dir"

if [[ ! -d $src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch "$git_tag" "$git_url" "$src_dir"
fi

cd "$src_dir"

./autogen.sh

cd "$bld_dir"

"$src_dir/configure" --prefix="$HOME/.local/stow/$pkg_tag"

execute_job make --jobs

make install
