#!/usr/bin/env bash

set -o errexit

_pkg_ver=${1:-2021.3.0}

_pkg_tag=tbb-$_pkg_ver

_pkg_dir=~/.local/stow/$_pkg_tag

_pkg_tar=~/.cache/stow/$_pkg_tag.tgz

_pkg_url=https://github.com/oneapi-src/oneTBB/releases/download/v$_pkg_ver/oneapi-tbb-$_pkg_ver-lin.tgz

if [[ ! -f $_pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$_pkg_tar" "$_pkg_url"
fi

mkdir -p "$_pkg_dir" && cd "$_"

tar xvf "$_pkg_tar" --strip-components 1

mv "$_pkg_dir/lib/intel64/gcc4.8" "$_pkg_dir/lib-tmp"

mv "$_pkg_dir/lib/cmake" "$_pkg_dir/lib-tmp"

rm --recursive "$_pkg_dir/lib"

mv "$_pkg_dir"/lib{-tmp,}

cat << EOF > "$_pkg_dir/.stow-local-ignore"
^/\.git.*
^/LICENSE.txt$
^/README.md$
^/env$
^/third-party-programs.txt$
EOF
