#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-12.0.1}

pkg_tag=llvm-$pkg_ver

git_url=https://github.com/llvm/llvm-project.git

git_tag=llvmorg-$pkg_ver

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build

if [[ ! -d $src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch "$git_tag" "$git_url" "$src_dir"
fi

cmake -GNinja\
      -S "$src_dir/llvm"\
      -B "$bld_dir"\
      -DCMAKE_BUILD_TYPE=Release\
      -DCMAKE_INSTALL_PREFIX="$HOME/.local/stow/$pkg_tag"\
      -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;openmp"\
      -DLLVM_TARGETS_TO_BUILD=host\
      -Wno-dev

execute_job cmake --build "$bld_dir"

cmake --install "$bld_dir"
