#!/usr/bin/env bash

set -o errexit

_pkg_ver=${1:-2.3.1}

_pkg_tag=stow-$_pkg_ver

_pkg_dir=~/.local/stow/$_pkg_tag

_pkg_tar=~/.cache/stow/$_pkg_tag.tgz

_pkg_url=http://ftp.gnu.org/gnu/stow/stow-$_pkg_ver.tar.gz

if [[ ! -f $_pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$_pkg_tar" "$_pkg_url"
fi

_src_dir=~/.local/src/$_pkg_tag
_bld_dir=~/.local/src/$_pkg_tag-build

mkdir -p "$_src_dir" "$_bld_dir"

tar xvf "$_pkg_tar" --strip-components 1 --directory "$_src_dir"

cd "$_bld_dir"

"$_src_dir/configure" --prefix="$_pkg_dir"

make && make install

cat << EOF > "$_pkg_dir/.stow-local-ignore"
^/share/info$
EOF
