#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-1.10.2}

pkg_tag=ninja-$pkg_ver

pkg_zip=~/.cache/stow/$pkg_tag.zip

pkg_url=https://github.com/ninja-build/ninja/releases/download/v$pkg_ver/ninja-linux.zip

if [[ ! -f $pkg_zip ]]; then
    curl --fail --location --create-dirs --output "$pkg_zip" "$pkg_url"
fi

mkdir -p ~/.local/stow/$pkg_tag/bin && cd "$_"

unzip "$pkg_zip"
