#!/usr/bin/env bash

set -o errexit

_pkg_ver_dbg=${1:-3.6.14}

_pkg_ver=${_pkg_ver_dbg%-dbg}

# If the version has a "-dbg" suffix, build the debug version.
if [[ $_pkg_ver != $_pkg_ver_dbg ]]; then
    _pkg_dbg=1
fi

_pkg_tag=cpython-$_pkg_ver

_git_url=https://github.com/python/cpython.git

_git_tag=v$_pkg_ver

_src_dir=~/.local/src/$_pkg_tag
_bld_dir=~/.local/src/$_pkg_tag-build${_pkg_dbg:+-dbg}

mkdir --parents "$_src_dir" "$_bld_dir"

if [[ ! -d $_src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch $_git_tag "$_git_url" "$_src_dir"
fi

cd "$_bld_dir"

"$_src_dir/configure" ${_pkg_dbg:+--with-pydebug} --prefix="$HOME/.local/stow/$_pkg_tag${_pkg_dbg:+-dbg}"

execute_job make --jobs

make altinstall
