#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-2.3.1}

pkg_tag=stow-$pkg_ver

pkg_dir=~/.local/stow/$pkg_tag

pkg_tar=~/.cache/stow/$pkg_tag.tgz

pkg_url=http://ftp.gnu.org/gnu/stow/stow-$pkg_ver.tar.gz

if [[ ! -f $pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$pkg_tar" "$pkg_url"
fi

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build

mkdir -p "$src_dir" "$bld_dir"

tar xvf "$pkg_tar" --strip-components 1 --directory "$src_dir"

cd "$bld_dir"

"$src_dir/configure" --prefix="$pkg_dir"

make && make install

cat << EOF > "$pkg_dir/.stow-local-ignore"
^/share/info$
EOF
