#!/usr/bin/env bash

set -o errexit

_pkg_ver=${1:-3.8.0}

_pkg_tag=protobuf-$_pkg_ver

_git_url=https://github.com/protocolbuffers/protobuf.git

_git_tag=v$_pkg_ver

_src_dir=~/.local/src/$_pkg_tag
_bld_dir=~/.local/src/$_pkg_tag-build

mkdir --parents "$_src_dir" "$_bld_dir"

if [[ ! -d $_src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch $_git_tag "$_git_url" "$_src_dir"
fi

cd "$_src_dir"

./autogen.sh

cd "$_bld_dir"

"$_src_dir/configure" "CFLAGS=-fPIC -fvisibility=hidden -std=c99" "CXXFLAGS=-fPIC -fvisibility=hidden -std=c++14"\
        --disable-shared\
        --prefix="$HOME/.local/stow/$_pkg_tag"

execute_job make --jobs

make install
