#!/usr/bin/env bash

set -eo pipefail

pkg_ver_dbg=${1:-3.6.14}

pkg_ver=${pkg_ver_dbg%-dbg}

# If the version has a "-dbg" suffix, build the debug version.
if [[ $pkg_ver != $pkg_ver_dbg ]]; then
    pkg_dbg=1
fi

pkg_tag=cpython-$pkg_ver

git_url=https://github.com/python/cpython.git

git_tag=v$pkg_ver

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build${pkg_dbg:+-dbg}

mkdir -p "$src_dir" "$bld_dir"

if [[ ! -d $src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch "$git_tag" "$git_url" "$src_dir"
fi

cd "$bld_dir"

"$src_dir/configure" ${pkg_dbg:+--with-pydebug} --prefix="$HOME/.local/stow/$pkg_tag${pkg_dbg:+-dbg}"

execute_job make --jobs

make altinstall
