#!/usr/bin/env bash

set -o errexit

_pkg_ver=${1:-3.21.0}

_pkg_tag=cmake-$_pkg_ver

_pkg_dir=~/.local/stow/$_pkg_tag

_pkg_tar=~/.cache/stow/$_pkg_tag.tgz

_pkg_url=https://github.com/Kitware/CMake/releases/download/v$_pkg_ver/cmake-$_pkg_ver-linux-x86_64.tar.gz

if [[ ! -f $_pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$_pkg_tar" "$_pkg_url"
fi

mkdir -p "$_pkg_dir" && cd "$_"

tar xvf "$_pkg_tar" --strip-components 1

cat << EOF > "$_pkg_dir/.stow-local-ignore"
^/doc$
^/man$
EOF
