#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-11.2.0}

pkg_tag=gcc-$pkg_ver

pkg_dir=~/.local/stow/$pkg_tag

git_url=https://github.com/gcc-mirror/gcc.git

git_tag=releases/gcc-$pkg_ver

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build

mkdir -p "$src_dir" "$bld_dir"

if [[ ! -d $src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules --branch "$git_tag" "$git_url" "$src_dir"
fi

cd "$src_dir"

contrib/download_prerequisites

cd "$bld_dir"

"$src_dir/configure" --enable-languages="c,c++,lto" --disable-multilib --with-system-zlib --prefix="$pkg_dir"

execute_job make --jobs

make install-strip

cat << EOF > "$pkg_dir/.stow-local-ignore"
^/share/info$
EOF
