#!/usr/bin/env bash

set -eo pipefail

pkg_tag=ctags

git_url=https://github.com/universal-ctags/ctags.git

src_dir=~/.local/src/$pkg_tag
bld_dir=~/.local/src/$pkg_tag-build

mkdir -p "$src_dir" "$bld_dir"

if [[ ! -d $src_dir/.git ]]; then
    git clone --depth 1 --shallow-submodules --recurse-submodules "$git_url" "$src_dir"
fi

cd "$src_dir"

./autogen.sh

cd "$bld_dir"

"$src_dir/configure" --prefix="$HOME/.local/stow/$pkg_tag"

execute_job make --jobs

make install
