#!/usr/bin/env bash

set -eo pipefail

pkg_ver=${1:-14.17.4}

pkg_tag=nodejs-$pkg_ver

pkg_dir=~/.local/stow/$pkg_tag

pkg_tar=~/.cache/stow/$pkg_tag.tar.xz

pkg_url=https://nodejs.org/dist/v$pkg_ver/node-v$pkg_ver-linux-x64.tar.xz

if [[ ! -f $pkg_tar ]]; then
    curl --fail --location --create-dirs --output "$pkg_tar" "$pkg_url"
fi

mkdir -p "$pkg_dir" && cd "$_"

tar xvf "$pkg_tar" --strip-components 1

cat << EOF > "$pkg_dir/.stow-local-ignore"
^/CHANGELOG.md$
^/LICENSE$
^/README.md$
EOF
